### PR TITLE
Fixed typo in main.yml

### PR DESCRIPTION
**Pull request by aditya-konarde**
Corrected 'resulsts' to 'results'

### CODE REVIEW

**Comment by Spredzy** [comment]
Hey @aditya-konarde. Thanks for contributing to this project.

The Github repository for this project is just a mirror, not PR will be merged here. Could you submit the patch to our Gerrit https://softwarefactory-project.io/r/#/admin/projects/ansible-role-openstack-certification

If you'd like me to walk you through the process, please let me know and I'll be happy to assist.

**Comment by aditya-konarde** [comment]
Hello @Spredzy . Could you please walk me through the process for submitting the patch to Gerrit, or give me a pointer to some docs on how I can contribute. Thanks for the help.

**Comment by goneri** [comment]
Hi @aditya-konarde,

I pushed your patch for review here: https://softwarefactory-project.io/r/10889

To do so, you just have to install the git-review package and call the `git review` command.

Cheers

**Comment by dsavineau** [comment]
The fix has been merged upstream so I close this one

**Pull request closed without merging**
